### ISSUE TITLE
CMAKE GUI 

### ISSUE THREAD

**Issue by emonkz** [Vordas/worktips-lite#1]
Hi, Vordaz

Can you explain about how to compile worktips from windows? bcause I confused on this step : 

> start CMake GUI and navigate to the repository folder using the field Where is the source code:

Ask : Is it our worktips wallet repo location? (Ex. D:/coin/worktips-lite-wallet)

> in the field Where to build the binaries: specify the build folder location

Ask:  No idea about this, maybe I must create new folder "build" in worktips wallet repo? (Ex. D:/coin/worktips-lite-wallet/build)

Regards,

**Comment by Vordas** [comment]
CMake GUI has two fields on top. The first field is the path to your source code (repo folder), and the second field is to specify the output folder for the build. You can leave the second field the same as the first field with a difference that at the end of the path add '/build' then click on 'configure' to configure build and create a folder called 'build' inside the main repo folder.

**Comment by emonkz** [comment]
Okay thank you, I'll try
