### ISSUE TITLE
Error Compile Wallet Windows

### ISSUE THREAD

**Issue by emonkz** [Vordas/worktips-lite#2]
Hi dev,

I tried to compile wallet on windows, but I got this this issue, maybe rocksdb issue, I already put the rockdb.lib inside build folder too.

> IMPORTANT: Unzip the rocksdb.zip located in the lib folder and put the unzipped file rocksdb.lib inside the folder build that was specified during step 3.

`Build FAILED.

       "D:\TEST\worktips-lite-wallet-master\build\Worktips.sln" (default target) (1) ->
       "D:\TEST\worktips-lite-wallet-master\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\miniupnpc\upnpc-static.vcxproj.metaproj" (default
        target) (7) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\miniupnpc\upnpc-static.vcxproj" (default target)
       (11) ->
       (ClCompile target) ->
         d:\test\worktips-lite-wallet-master\cryptonote\external\miniupnpc\miniupnpc.c(436): warning C4996: 'inet_addr'
       : Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warn
       ings [D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\miniupnpc\upnpc-static.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\miniupnpc\miniupnpc.c(521): warning C4996: 'inet_addr'
       : Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warn
       ings [D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\miniupnpc\upnpc-static.vcxproj]

       "D:\TEST\worktips-lite-wallet-master\build\Worktips.sln" (default target) (1) ->
       "D:\TEST\worktips-lite-wallet-master\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "D:\TEST\worktips-lite-wallet-master\build\Worktips.vcxproj.metaproj" (default target) (3) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\rocksdb\rocksdb.vcxproj.metaproj" (default target
       ) (6) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\rocksdb\rocksdb.vcxproj" (default target) (12) ->
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): warning C4189: 'erased': local variable is initialized but not referenced [D:\TEST\worktips-lite-wallet-m
       aster\build\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): warning C4189: 'erased': local variable is initialized but not referenced [D:\TEST\worktips-lite-wallet-m
       aster\build\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): warning C4189: 'erased': local variable is initialized but not referenced [D:\TEST\worktips-lite-wallet-m
       aster\build\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): warning C4189: 'erased': local variable is initialized but not referenced [D:\TEST\worktips-lite-wallet-m
       aster\build\cryptonote\external\rocksdb\rocksdb.vcxproj]

       "D:\TEST\worktips-lite-wallet-master\build\Worktips.sln" (default target) (1) ->
       "D:\TEST\worktips-lite-wallet-master\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "D:\TEST\worktips-lite-wallet-master\build\Worktips.vcxproj.metaproj" (default target) (3) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\rocksdb\rocksdb.vcxproj.metaproj" (default target
       ) (6) ->
       "D:\TEST\worktips-lite-wallet-master\build\cryptonote\external\rocksdb\rocksdb.vcxproj" (default target) (12) ->
       (ClCompile target) ->
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): error C2220: warning treated as error - no 'object' file generated [D:\TEST\worktips-lite-wallet-master\b
       uild\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): error C2220: warning treated as error - no 'object' file generated [D:\TEST\worktips-lite-wallet-master\b
       uild\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): error C2220: warning treated as error - no 'object' file generated [D:\TEST\worktips-lite-wallet-master\b
       uild\cryptonote\external\rocksdb\rocksdb.vcxproj]
         d:\test\worktips-lite-wallet-master\cryptonote\external\rocksdb\utilities\transactions\write_prepared_txn_db.h
       (281): error C2220: warning treated as error - no 'object' file generated [D:\TEST\worktips-lite-wallet-master\b
       uild\cryptonote\external\rocksdb\rocksdb.vcxproj]

    6 Warning(s)
    4 Error(s)
Time Elapsed 00:08:27.42`

![visual studio](https://user-images.githubusercontent.com/16758955/40568645-12875b74-60a6-11e8-85fd-35a9042bd032.png)

![visual studio](https://user-images.githubusercontent.com/16758955/40568943-01d1ffc6-60a8-11e8-9a46-6fdf0aaab339.png)
![vs](https://user-images.githubusercontent.com/16758955/40568944-0207b788-60a8-11e8-8440-0fdb56dd7473.png)

**Comment by Vordas** [comment]
Closing due to source repository being updated to v1.0.2.3 and new build instructions being added to repo very soon.
