### ISSUE TITLE
Connection error when using default pool during mining.

### ISSUE THREAD

**Issue by sergeysamonte** [Vordas/worktips-lite#3]

**Comment by Vordas** [comment]
Hi. Please use the host/port/difficulty fields in the wallet's mining section to add the pool you would like to mine in. Once added, drag it to the top of the list of pools. The top pool in the list is being mined by the wallet miner. 

The new official pool host is worktips.work and the mining port for the wallet is 3333. You can also select any community pool to mine in, by visiting any pool's 'Getting started' section to get the host and port values for connection. You can find the list of all active pools here: http://worktips.info

**Comment by Vordas** [comment]
Closing. Feel free to re-open it if the issue persists
